name: Release Drafter

on:
  workflow_call:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
        uses: jenkinsci/gitlab-plugin/.github/workflows/release-drafter.yml@main

